## Keadaan Terbelit dalam 2-Qubit

$$| \psi \rangle_{AB} = c_{00}|00\rangle + c_{01}|01\rangle + c_{10}|10\rangle + c_{11}|11\rangle$$

::: {.fragment}
*Apakah keadaan gabungan $| \psi \rangle_{AB}$ selalu menyatu, atau sebenarnya dapat diurai menjadi dua qubit berbeda?*
:::

::: {.fragment}
$$| \psi \rangle_{AB} = | \psi \rangle_A \otimes | \psi \rangle_B$$

- Keadaan Qubit $A$: $| \psi \rangle_A = x_0|0\rangle + x_1|1\rangle$
- Keadaan Qubit $B$: $| \psi \rangle_B = y_0|0\rangle + y_1|1\rangle$
:::

::: {.columns}

::: {.column width="55%" .fragment}
$$
\begin{aligned}
| \psi \rangle_{AB} &= (x_0|0\rangle + x_1|1\rangle)(y_0|0\rangle + y_1|1\rangle) \\
&= x_0|0\rangle(y_0|0\rangle + y_1|1\rangle) + x_1|1\rangle(y_0|0\rangle + y_1|1\rangle) \\
&= x_0 y_0|00\rangle + x_0 y_1|01\rangle + x_1 y_0|10\rangle + x_1 y_1|11\rangle\\
&= c_{00}|00\rangle + c_{01}|01\rangle + c_{10}|10\rangle + c_{11}|11\rangle
\end{aligned}
$$

#### Hubungan Koefisien:
::: {.columns}
::: {.column width="50%" .fragment}
- Basis $|00\rangle \rightarrow c_{00} = x_0 y_0$
- Basis $|01\rangle \rightarrow c_{01} = x_0 y_1$
:::
::: {.column width="50%" .fragment}
- Basis $|10\rangle \rightarrow c_{10} = x_1 y_0$
- Basis $|11\rangle \rightarrow c_{11} = x_1 y_1$
:::
:::

:::

::: {.column width="45%" .fragment}

- **Keadaan Terpisah:** Jika terdapat nilai $x_0, x_1, y_0, y_1$ nyata yang memenuhi sistem hubungan persamaan di samping.

$$| \psi \rangle_{AB} = | \psi \rangle_A \otimes | \psi \rangle_B$$

- **Keadaan Terbelit:** Jika tidak ada nilai $x_0, x_1, y_0, y_1$ nyata yang memenuhi sistem hubungan persamaan di samping.

$$| \psi \rangle_{AB} \neq | \psi \rangle_A \otimes | \psi \rangle_B$$

:::

:::

## Keterbelitan dalam Sistem 3-Qubit

$$|\psi\rangle_{ABC} = c_{000}|000\rangle + c_{001}|001\rangle + \dots + c_{111}|111\rangle$$

::: {.fragment}
*Bagaimana kita menguji dan mengklasifikasikan jenis keterbelitan ketika sistem meluas menjadi tiga qubit?*
:::

::: {.fragment}
:::{.columns}
:::{.column width="30%" .fragment}
$$|\psi\rangle_{ABC} = |\psi\rangle_A \otimes |\psi\rangle_B \otimes |\psi\rangle_C$$

- $|\psi\rangle_A = x_0|0\rangle + x_1|1\rangle$, 

- $|\psi\rangle_B = y_0|0\rangle + y_1|1\rangle$, dan 

- $|\psi\rangle_C = z_0|0\rangle + z_1|1\rangle$.
:::

:::{.column width="70%" .fragment}
$$
\begin{aligned}
| \psi \rangle_{ABC} &= (x_0|0\rangle + x_1|1\rangle)(y_0|0\rangle + y_1|1\rangle)(z_0|0\rangle + z_1|1\rangle) \\
&\quad + x_1 y_0|10\rangle(z_0|0\rangle + z_1|1\rangle) + x_1 y_1|11\rangle(z_0|0\rangle + z_1|1\rangle) \\
&= x_0 y_0 z_0|000\rangle + x_0 y_0 z_1|001\rangle + x_0 y_1 z_0|010\rangle + x_0 y_1 z_1|011\rangle \\
&\quad + x_1 y_0 z_0|100\rangle + x_1 y_0 z_1|101\rangle + x_1 y_1 z_0|110\rangle + x_1 y_1 z_1|111\rangle \\
&= c_{000}|000\rangle + c_{001}|001\rangle + c_{010}|010\rangle + c_{011}|011\rangle \\
&\quad + c_{100}|100\rangle + c_{101}|101\rangle + c_{110}|110\rangle + c_{111}|111\rangle
\end{aligned}
$$
:::

:::
:::

::: {.columns}

:::{.fragment}
#### Hubungan Koefisien sebagai syarat Terpisah Sempurna:
:::
<!-- Ekspansi perkalian tiga arah menghasilkan 8 sistem persamaan koefisien: -->
::: {.column width="50%" .fragment}

- Basis $|000\rangle \rightarrow c_{000} = x_0 y_0 z_0$

- Basis $|001\rangle \rightarrow c_{001} = x_0 y_0 z_1$

- Basis $|010\rangle \rightarrow c_{010} = x_0 y_1 z_0$

- Basis $|011\rangle \rightarrow c_{011} = x_0 y_1 z_1$
:::

::: {.column width="50%" .fragment}

- Basis $|100\rangle \rightarrow c_{100} = x_1 y_0 z_0$

- Basis $|101\rangle \rightarrow c_{101} = x_1 y_0 z_1$

- Basis $|110\rangle \rightarrow c_{110} = x_1 y_1 z_0$

- Basis $|111\rangle \rightarrow c_{111} = x_1 y_1 z_1$
:::

:::

---

## Jenis Keterbelitan 3-Qubit

Berdasarkan sistem persamaan hubungan koefisien sebelumnya, jika tidak ada solusi nilai $\{x_i, y_j, z_k\}$ yang memenuhi, sistem 3-qubit tersebut
memiliki 2 kemungkinan bentuk keterbelitan:

::: {.columns}

::: {.column width="50%" .fragment}
### 1. Terbelit Sebagian
bentuk 2-Qubit dari 3-Qubit tidak bisa difaktorisasi dalam perkalian tensor dan

**Bentuk umum Terbelit sebagian :**
$$|\psi\rangle_{A|BC} = |\psi\rangle_A \otimes |\psi\rangle_{BC}$$

$$|\psi\rangle_{AB|C} = |\psi\rangle_{AB} \otimes |\psi\rangle_C$$


$$|\psi\rangle_{B|AC} = |\psi\rangle_B \otimes |\psi\rangle_{AC}$$
:::

::: {.column width="50%" .fragment}
### 2. Terbelit sejati

bentuk 3-Qubit tidak bisa difaktorisasi dalam perkalian tensor dan
$$|\psi\rangle_{ABC} \neq |\psi\rangle_A \otimes |\psi\rangle_B \otimes |\psi\rangle_C$$

Keterbelitan Sejati ini terdapat 2 bentuk 

- **Keadaan GHZ (Greenberger-Horne-Zeilinger):**
  $$|GHZ\rangle = g_000 |000\rangle + g_000 |111\rangle$$

- **Keadaan W:**
  $$|W\rangle =  w_100 |100\rangle + w_010 |010\rangle +w_001 |001\rangle$$
:::

:::

## Representasi Matriks & Transformasi Uniter 3-Qubit

<!-- Berdasarkan dasar representasi matriks basis keadaan:
$$|0\rangle = \begin{pmatrix} 1 \\ 0 \end{pmatrix} \quad \text{dan} \quad |1\rangle = \begin{pmatrix} 0 \\ 1 \end{pmatrix}$$ -->

::: {.columns}

::: {.column width="35%" .fragment}
### Representasi Vektor
Dari bentuk 3 Qubit tadi

:::{.r-stack}

:::{.fragment .fade-in-then-out}

$$|\psi\rangle_{ABC} = c_{000}|000\rangle + c_{001}|001\rangle + \dots + c_{111}|111\rangle$$
:::

:::{.fragment}
$$
|\psi\rangle_{ABC} = \begin{pmatrix} 
c_{000} \\ c_{001} \\ c_{010} \\ c_{011} \\ 
c_{100} \\ c_{101} \\ c_{110} \\ c_{111} 
\end{pmatrix}
$$
:::

:::

:::{.fragment}
Membentuk basis paling sederhana $|000\rangle$ menuju keadaan $|\psi\rangle_{ABC}$ melalui matriks transformasi $M$ berukuran $8 \times 8$:
$$|\psi\rangle_{ABC} = M |000\rangle$$
:::


:::

::: {.column width="65%" .fragment}
### Jenis Matriks
Berdasarkan syarat normalisasi :

:::{.r-stack}
:::{.fragment .fade-in-then-out}
$$
\begin{align*}
\langle\psi|\psi\rangle_{ABC} &= 1\\
\langle000| M^\dagger M |000\rangle &= 1\\
\end{align*}
$$
:::
:::{.fragment}
$$
\begin{align*}
\langle\psi|\psi\rangle_{ABC} &= 1\\
\langle000| \boxed{M^\dagger M} |000\rangle &= 1\\
\end{align*}
$$
:::
:::
didapatkan $M^\dagger M = I$ dengan Matriks $M$ uniter yang dapat di modelkan dari grup lie $SU(N)$

:::::::::::: {.columns style="display: flex; justify-content: space-between;"}
::::: {.column .fragment .card .info-box width="33%" style="text-align: left;"}
::: {.fragment .strike}
$$ M=SU(8) $$
:::

::: {.fragment .strike}
$$\Downarrow$$

Terlalu banyak parameter (63 Parameter)
:::
:::::

::::: {.column .fragment .card .success-box width="33%" style="text-align: left;"}
::: {.fragment .strike}
$$ M=SU(2) \otimes SU(2)\\
 \otimes SU(2)$$
:::

::: {.fragment .strike}
$$\Downarrow$$ Selalu menghasilkan keadaan yang terpisah
:::
:::::

::::: {.column .fragment .card .warning-box width="33%" style="text-align: left;"}
::: fragment
$$ M=SU(4) \otimes SU(2)\\ 
M=SU(2) \otimes SU(4)$$
:::

:::{.fragment}
::: {.fragment .grow}
$$\Downarrow$$ dapat menghasilkan keadaan 3 qubit dengan semua jenis keterbelitannya
:::
:::

:::::
::::::::::::
<!-- ::: {.fragment}
Agar persamaan di atas selalu terpenuhi untuk setiap keadaan basis kuantum, maka bagian matriks di tengah wajib bernilai identitas ($\mathbf{I}$):
$$M^\dagger M = I \quad \rightarrow \quad M^\dagger = M^{-1}$$

Matriks transformasi $M$ berukuran $8 \times 8$ harus berupa **Matriks Uniter**.
::: -->
:::

:::

---
