## Kontruksi Matriks Uniter Qubit

$$\boxed{|\psi'\rangle = M |000\rangle}$$

dengan $M$ adalah matriks uniter yang dibangun oleh grup $SU(N)$

:::::::::::: {.columns style="display: flex; justify-content: space-between;"}
::::: {.column .fragment .card .info-box width="33%" style="text-align: left;"}
::: {.fragment .strike}
$$ M=SU(8) $$
:::

::: {.fragment .strike}
$$\Downarrow$$

Terlalu banyak parameter (63 Parameter)
:::
:::::

::::: {.column .fragment .card .success-box width="33%" style="text-align: left;"}
::: {.fragment .strike}
$$ M=SU(2) \otimes SU(2) \otimes SU(2)$$
:::

::: {.fragment .strike}
$$\Downarrow$$ Selalu menghasilkan keadaan yang terpisah
:::
:::::

::::: {.column .fragment .card .warning-box width="33%" style="text-align: left;"}
::: fragment
$$ M=SU(4) \otimes SU(2)$$ atau $$ M=SU(2) \otimes SU(4)$$
:::

::: {.fragment .grow}
$$\Downarrow$$ dapat menghasilkan keadaan 3 qubit dengan semua jenis keterbelitannya
:::
:::::
::::::::::::

<!-- $$|\psi'\rangle = M |\psi\rangle \rightarrow \langle \psi'|\psi'\rangle = 1 $$ -->

## Kontruksi Parameterisasi SU(4) dan SU(2)

**Konstruksi SU(2)**

Dari persamaan $$\boxed{U_{SU(2)}(\theta, \phi, \lambda) = e^{i\lambda \sigma_z} e^{i\theta \sigma_y} e^{i\phi \sigma_z}}$$ dipilih parameter $\theta=\phi=\lambda=0$ sehingga $U_{SU(2) }(0,0,0) = I$

**Konstruksi SU(4)**

Dari persamaan $$\boxed{\begin{align}
U_{SU(4)} &=
e^{i\lambda_3\alpha_1}
e^{i\lambda_2\alpha_2}
e^{i\lambda_3\alpha_3}
e^{i\lambda_5\alpha_4}
e^{i\lambda_3\alpha_5}
e^{i\lambda_{10}\alpha_6}
e^{i\lambda_3\alpha_7}
e^{i\lambda_2\alpha_8}
e^{i\lambda_3\alpha_9}
e^{i\lambda_5\alpha_{10}}
e^{i\lambda_3\alpha_{11}}
e^{i\lambda_2\alpha_{12}}\\
&
e^{i\lambda_3\alpha_{13}}
e^{i\lambda_8\alpha_{14}}
e^{i\lambda_{15}\alpha_{15}}\\
\end{align}}$$ dan parameter berupa $\alpha_2,\alpha_4,\alpha_6,\alpha_8,\alpha_{10},\alpha_{12}$ secara berpasangan dan dengan pasangan nilai yang dipilih $\frac{\pi}{12},\frac{\pi}{2}$. Selanjutnya,Pengembangan matriks dari produk tensor untuk model

$$U_{24} = I \otimes U_{SU(4)}(\alpha_i,\alpha_j)$$

dan

$$U_{42} = U_{SU(4)}(\alpha_i,\alpha_j) \otimes I $$

------------------------------------------------------------------------

::::: r-stack
::: {.fragment .fade-out}
sebagai contoh pada parameter $\alpha_2$ dan $\alpha_4$: $$U_4(\alpha_{2},\alpha_{4})
=
\begin{pmatrix}
\cos\alpha_{2}\cos\alpha_{4} &
\sin\alpha_{2} &
\sin\alpha_{4}\cos\alpha_{2} &
0\\
-\sin\alpha_{2}\cos\alpha_{4} &
\cos\alpha_{2} &
-\sin\alpha_{2}\sin\alpha_{4} &
0\\
-\sin\alpha_{4} &
0 &
\cos\alpha_{4} &
0\\
0&0&0&1
\end{pmatrix}$$ dan $$\begin{align*}
U_{42}(\alpha_{2},\alpha_{4})
&=U_4(\alpha_{2},\alpha_{4})\otimes U_2,\\
\\
U_{42}(\alpha_{2},\alpha_{4})
&=
\begin{pmatrix}
\cos\alpha_{2}\cos\alpha_{4} &0&\sin\alpha_{2}&0&\sin\alpha_{4}\cos\alpha_{2}&0&0&0\\
0&\cos\alpha_{2}\cos\alpha_{4}&0&\sin\alpha_{2}&0&\sin\alpha_{4}\cos\alpha_{2}&0&0\\
-\sin\alpha_{2}\cos\alpha_{4}&0&\cos\alpha_{2}&0&-\sin\alpha_{2}\sin\alpha_{4}&0&0&0\\
0&-\sin\alpha_{2}\cos\alpha_{4}&0&\cos\alpha_{2}&0&-\sin\alpha_{2}\sin\alpha_{4}&0&0\\
-\sin\alpha_{4}&0&0&0&\cos\alpha_{4}&0&0&0\\
0&-\sin\alpha_{4}&0&0&0&\cos\alpha_{4}&0&0\\
0&0&0&0&0&0&1&0\\
0&0&0&0&0&0&0&1
\end{pmatrix}.
\end{align*}$$
:::

::: fragment
dan

$$\begin{align*}
U_{24}(\alpha_{2},\alpha_{4})
&=U_2\otimes U_4(\alpha_{2},\alpha_{4})\\
&=
\begin{pmatrix}
\cos\alpha_{2}\cos\alpha_{4}&\sin\alpha_{2}&\sin\alpha_{4}\cos\alpha_{2}&0&0&0&0&0\\
-\sin\alpha_{2}\cos\alpha_{4}&\cos\alpha_{2}&-\sin\alpha_{2}\sin\alpha_{4}&0&0&0&0&0\\
-\sin\alpha_{4}&0&\cos\alpha_{4}&0&0&0&0&0\\
0&0&0&1&0&0&0&0\\
0&0&0&0&\cos\alpha_{2}\cos\alpha_{4}&\sin\alpha_{2}&\sin\alpha_{4}\cos\alpha_{2}&0\\
0&0&0&0&-\sin\alpha_{2}\cos\alpha_{4}&\cos\alpha_{2}&-\sin\alpha_{2}\sin\alpha_{4}&0\\
0&0&0&0&-\sin\alpha_{4}&0&\cos\alpha_{4}&0\\
0&0&0&0&0&0&0&1
\end{pmatrix}.
\end{align*}$$
:::
:::::

## Pembangkitan Keadaan 3-Qubit dari Keadaan Awal $|000\rangle$ {auto-animate="true"}

::::: columns
::: {.column width="40%"}
### Variasi Pertama

Pada Variasi $(SU(2) \otimes SU(4))(SU(4) \otimes SU(2))=U_{24} U_{42}$

$$\boxed{\begin{align*}
{\left|\psi_1 (\alpha_i,\alpha_j)\right\rangle}_{x} &= U_{42(x)}(\alpha_{i}, \alpha_{j})\,{\left|000\right\rangle}\\
\end{align*}}$$

$$\boxed{\begin{align*}
{\left|\phi_1 (\alpha_i,\alpha_j)\right\rangle} &= U_{24(x)}(\alpha_{i}, \alpha_{j})\,{\left|\psi (\alpha_i,\alpha_j)\right\rangle}\\ 
&=U_{24(x)}(\alpha_{i}, \alpha_{j}) U_{42(x)}(\alpha_{i}, \alpha_{j})\,{\left|000\right\rangle}
\end{align*}}$$
:::

::: {.column width="60%"}
### Variasi Kedua

Pada Variasi $(SU(2) \otimes SU(4))(SU(4) \otimes SU(2))=U_{42} U_{24}$

$$ \boxed{{\left|\psi_2 (\alpha_i,\alpha_j)\right\rangle}=U_{24(x)}(\alpha_{i}, \alpha_{j})\,{\left|000\right\rangle}}$$

$$\boxed{\begin{align*}
{\left|\phi_2 (\alpha_i,\alpha_j)\right\rangle} &= U_{42(x)}(\alpha_{i}, \alpha_{j})\,{\left|\psi_2 (\alpha_i,\alpha_j)\right\rangle}\\ 
&=U_{42(x)}(\alpha_{i}, \alpha_{j}) U_{24(x)}(\alpha_{i}, \alpha_{j})\,{\left|000\right\rangle}\end{align*}}$$
:::
:::::

## Pembangkitan Keadaan 3-Qubit dari Keadaan Awal $|000\rangle$ {auto-animate="true"}

::::: columns
::: {.column width="40%"}
### Contoh Tahap 1 pada Variasi pertama

$$\begin{align*}
{\left|\psi (\alpha_2,\alpha_4)\right\rangle} &= U_{42}(\alpha_{2}, \alpha_{4})\,{\left|000\right\rangle}\\
 &=  \begin{pmatrix}\cos{\left(\alpha_{2} \right)} \cos{\left(\alpha_{4} \right)}\\ 0 \\- \sin{\left(\alpha_{2} \right)} \cos{\left(\alpha_{4} \right)}\\ 0 \\- \sin{\left(\alpha_{4} \right)}\\ 0 \\ 0 \\ 0 \end{pmatrix}  \\
% &= \cos{\left(\alpha_{2} \right)} \cos{\left(\alpha_{4} \right)} {\left|000\right\rangle} - \sin{\left(\alpha_{2} \right)} \cos{\left(\alpha_{4} \right)} {\left|010\right\rangle} - \sin{\left(\alpha_{4} \right)} {\left|100\right\rangle}
\end{align*}$$
:::

::: {.column width="60%"}
### Contoh Tahap 2 pada Variasi pertama

$$\begin{align*}
{\left|\phi (\alpha_2,\alpha_4)\right\rangle} &= U_{24}(\alpha_{2}, \alpha_{4})\,{\left|\psi (\alpha_2,\alpha_4)\right\rangle}\\ 
&=  \begin{pmatrix}\frac{\cos{\left(2 \alpha_{2} \right)}}{4} + \frac{\cos{\left(2 \alpha_{4} \right)}}{4} + \frac{\cos{\left(2 \left(\alpha_{2} + \alpha_{4}\right) \right)}}{4} + \frac{1}{4}\\- \sin{\left(\alpha_{2} \right)} \cos{\left(\alpha_{4} \right)} \cos{\left(\alpha_{2} + \alpha_{4} \right)}\\- \frac{\sin{\left(\alpha_{2} \right)}}{2} - \frac{\sin{\left(\alpha_{2} + 2 \alpha_{4} \right)}}{2}\\ 0 \\\frac{\sin{\left(\alpha_{2} - 2 \alpha_{4} \right)}}{4} - \frac{\sin{\left(\alpha_{2} + 2 \alpha_{4} \right)}}{4}\\\frac{\cos{\left(\alpha_{2} - 2 \alpha_{4} \right)}}{4} - \frac{\cos{\left(\alpha_{2} + 2 \alpha_{4} \right)}}{4}\\\sin^{2}{\left(\alpha_{4} \right)}\\ 0 \end{pmatrix}  \\
% &= \left(\frac{\cos{\left(2 \alpha_{2} \right)}}{4} + \frac{\cos{\left(2 \alpha_{4} \right)}}{4} + \frac{\cos{\left(2 \alpha_{2} + 2 \alpha_{4} \right)}}{4} + \frac{1}{4}\right) {\left|000\right\rangle} - \sin{\left(\alpha_{2} \right)} \cos{\left(\alpha_{4} \right)} \cos{\left(\alpha_{2} + \alpha_{4} \right)} {\left|001\right\rangle} \\
% &\quad + \left(- \frac{\sin{\left(\alpha_{2} \right)}}{2} - \frac{\sin{\left(\alpha_{2} + 2 \alpha_{4} \right)}}{2}\right) {\left|010\right\rangle} + \left(\frac{\sin{\left(\alpha_{2} - 2 \alpha_{4} \right)}}{4} - \frac{\sin{\left(\alpha_{2} + 2 \alpha_{4} \right)}}{4}\right) {\left|100\right\rangle} \\
% &\quad + \left(\frac{\cos{\left(\alpha_{2} - 2 \alpha_{4} \right)}}{4} - \frac{\cos{\left(\alpha_{2} + 2 \alpha_{4} \right)}}{4}\right) {\left|101\right\rangle} + \sin^{2}{\left(\alpha_{4} \right)} {\left|110\right\rangle}
\end{align*}$$
:::
:::::

## Pembangkitan Keadaan 3-Qubit dari Keadaan Awal $|000\rangle$ {auto-animate="true"}

:::::: columns
::::: columns
::: {.column width="40%"}
### Tahap 1

$$\begin{aligned}
|\psi (\alpha_2,\alpha_4)\rangle
&= U_{42}(\alpha_{2}, \alpha_{4})\,|000\rangle \\
&= \cos(\alpha_{2})\cos(\alpha_{4})\,|000\rangle \\
&\quad - \sin(\alpha_{2})\cos(\alpha_{4})\,|010\rangle \\
&\quad - \sin(\alpha_{4})\,|100\rangle
\end{aligned}$$
:::

::: {.column width="60%"}
### Tahap 2

$$\begin{aligned}
|\phi (\alpha_2,\alpha_4)\rangle
&= U_{24}(\alpha_{2}, \alpha_{4})\,|\psi (\alpha_2,\alpha_4)\rangle \\[4pt]
&= \left(
\frac{\cos(2\alpha_{2})}{4}
+ \frac{\cos(2\alpha_{4})}{4}
+ \frac{\cos(2\alpha_{2}+2\alpha_{4})}{4}
+ \frac{1}{4}
\right)|000\rangle \\[4pt]
&\quad - \sin(\alpha_{2})\cos(\alpha_{4})\cos(\alpha_{2}+\alpha_{4})\,|001\rangle \\[4pt]
&\quad - \frac{\sin(\alpha_{2}) + \sin(\alpha_{2}+2\alpha_{4})}{2}\,|010\rangle \\[4pt]
&\quad + \frac{\sin(\alpha_{2}-2\alpha_{4}) - \sin(\alpha_{2}+2\alpha_{4})}{4}\,|100\rangle \\[4pt]
&\quad + \frac{\cos(\alpha_{2}-2\alpha_{4}) - \cos(\alpha_{2}+2\alpha_{4})}{4}\,|101\rangle \\[4pt]
&\quad + \sin^{2}(\alpha_{4})\,|110\rangle
\end{aligned}$$
:::
:::::
::::::

## Pembangkitan Keadaan 3-Qubit dari Keadaan Awal {auto-animate="true"}

::::: columns
::: {.column width="50%"}
### Variasi Pertama ($U_{24} U_{42}$)

$$\boxed{\begin{align*}
{\left|\psi_1 (\alpha_i,\alpha_j)\right\rangle}_{x} &= U_{42(x)}(\alpha_{i}, \alpha_{j})\,{\left|000\right\rangle} \\
\\
{\left|\phi_1 (\alpha_i,\alpha_j)\right\rangle}_{x} &= U_{24(x)}(\alpha_{i}, \alpha_{j}) U_{42(x)}(\alpha_{i}, \alpha_{j})\,{\left|000\right\rangle}
\end{align*}}$$
:::

::: {.column width="50%"}
### Variasi Kedua ($U_{42} U_{24}$)

$$\boxed{\begin{align*}
{\left|\psi_2 (\alpha_i,\alpha_j)\right\rangle}_{x} &= U_{24(x)}(\alpha_{i}, \alpha_{j})\,{\left|000\right\rangle} \\
\\
{\left|\phi_2 (\alpha_i,\alpha_j)\right\rangle}_{x} &= U_{42(x)}(\alpha_{i}, \alpha_{j}) U_{24(x)}(\alpha_{i}, \alpha_{j})\,{\left|000\right\rangle}
\end{align*}}$$
:::
:::::

## Pembangkitan Keadaan 3-Qubit dari Keadaan Awal {auto-animate="true"}

::::::::: columns
::::: {.column width="50%"}
### Variasi Pertama ($U_{24} U_{42}$)

$$\boxed{\begin{align*}
{\left|\psi_1 (\alpha_i,\alpha_j)\right\rangle}_{x} &= U_{42(x)}(\alpha_{i}, \alpha_{j})\,{\left|000\right\rangle} \\
\\
{\left|\phi_1 (\alpha_i,\alpha_j)\right\rangle}_{x} &= U_{24(x)}(\alpha_{i}, \alpha_{j}) U_{42(x)}(\alpha_{i}, \alpha_{j})\,{\left|000\right\rangle}
\end{align*}}$$

$$\Downarrow$$

::: {.card .info-box}
$$\text{Entropi von Neumann}$$
:::

$$\Downarrow$$

::: {.card .success-box}
$$\text{Jenis Keterbelitan}$$
:::
:::::

::::: {.column width="50%"}
### Variasi Kedua ($U_{42} U_{24}$)

$$\boxed{\begin{align*}
{\left|\psi_2 (\alpha_i,\alpha_j)\right\rangle}_{x} &= U_{24(x)}(\alpha_{i}, \alpha_{j})\,{\left|000\right\rangle} \\
\\
{\left|\phi_2 (\alpha_i,\alpha_j)\right\rangle}_{x} &= U_{42(x)}(\alpha_{i}, \alpha_{j}) U_{24(x)}(\alpha_{i}, \alpha_{j})\,{\left|000\right\rangle}
\end{align*}}$$

$$\Downarrow$$

::: {.card .info-box}
$$\text{Entropi von Neumann}$$
:::

$$\Downarrow$$

::: {.card .success-box}
$$\text{Jenis Keterbelitan}$$
:::
:::::
:::::::::